#spring:
#  jackson:
#    default-property-inclusion: non_null
#    deserialization:
#      read-unknown-enum-values-as-null: true
#      fail-on-unknown-properties: false
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        order_by:
#          default_null_ordering: last
logging:
  level:
    root: ERROR
info:
  app:
    name: 'webscraper'
    description: 'webscraper'
    version: '{version}'
server:
  port: 80
  servlet:
    context-path: '/webscraper-api'
  compression:
    enabled: true
  tomcat:
    max-threads: 400
    mbeanregistry:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: '/actuator'
  metrics:
    export:
      graphite:
        enabled: false
amazon:
  region: 'ap-southeast-2'
  dynamodb:
    endpoint:
      url: http://dynamodb-local:8000/
