
logging:
  level:
    root: DEBUG
info:
  app:
    name: 'webscraper'
    description: 'webscraper'
    version: '{version}'
server:
  port: 80
  servlet:
    context-path: '/webscraper-api'
  compression:
    enabled: true
  tomcat:
    max-threads: 400
    mbeanregistry:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: '/actuator'
  metrics:
    export:
      graphite:
        enabled: false
amazon:
  region: ap-southeast-2
  sqs:
    queue:
      url: https://sqs.ap-southeast-2.amazonaws.com/142621353074/webscraper-sqs-queue
      name: webscraper-sqs-queue
    dlq:
      url: https://sqs.ap-southeast-2.amazonaws.com/142621353074/webscraper-sqs-dlq
      name: webscraper-sqs-dlq
